language: node_js
node_js:
  - "0.12"
  - "4.3.1"
  - "5.6.0"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "5.4.1" 
script: 
  - npm test
  - npm run-script ctest
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script: "cp ./coverage/Fire*/lcov.info ./coverage && ls -cal ./coverage && npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"
