language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "6"
script: 
  - npm test
  - npm run-script ctest
  - npm run-script report
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script: 
  - ls -cal
  - ls -cal ./coverage
  - ls -cal ./coverage/"Firefox 31.0.0 (Linux 0.0.0)"
  - npm install coveralls@2.11.9
  - cat ./coverage/lcov.info | coveralls
